version: 2.1
jobs:
  latest_latest:
    docker:
      - image: circleci/node:lts-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: sh test.sh latest latest
  latest_next:
    docker:
      - image: circleci/node:lts-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: sh test.sh latest next
  next_latest:
    docker:
      - image: circleci/node:lts-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: sh test.sh next latest
  next_next:
    docker:
      - image: circleci/node:lts-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: sh test.sh next next

# Workflows
workflows:
  version: 2.1
  test:
    jobs:
      - latest_latest
      - latest_next
      - next_latest
      - next_next